feat(UIShell): add persistentHamburgerMenu prop to Header
IBM/carbon-components-svelte pull request #396
Opened 2020-11-12 14:08 UTC by josefaidt

- adds `persistentHamburgerMenu` prop to Header component
- fixes collapse logic in SideNav
- overrides `isSideNavOpen` logic when persisting hamburger menu

ref #374

2020-11-13 18:34 UTC, albertms10 approved these changes

2020-11-13 18:43 UTC, josefaidt commented on src/UIShell/SideNav/SideNav.svelte
> +  class:bx--side-nav--collapsed="{fixed ? !isOpen && fixed : !isOpen}"
😆 oh goodness. Applied the simplification

2020-11-16 06:08 UTC, albertms10 commented on src/UIShell/SideNav/SideNav.svelte
> +  class:bx--side-nav--collapsed="{fixed ? !isOpen && fixed : !isOpen}"
Have you already commited this fix? It does not appear as so here!… 🤔

2020-11-16 06:08 UTC, albertms10 approved these changes

2020-11-17 00:50 UTC, metonym requested changes
Could you add a [usage example](https://carbon-svelte.vercel.app/components/UIShell#usage)?

2020-11-18 14:47 UTC, josefaidt commented on src/UIShell/SideNav/SideNav.svelte
> +  class:bx--side-nav--collapsed="{fixed ? !isOpen && fixed : !isOpen}"
My apologies, just pushed it.

2020-11-18 16:26 UTC, metonym approved these changes

2020-11-18 16:26 UTC, merged