Add html input attributes to ToolbarSearchProps
IBM/carbon-components-svelte pull request #647
Opened 2021-05-14 13:03 UTC by gregorw

Fixes #646

ToolbarSearchProps are missing type definitions for $$restProops. With this PR `svelte-check` no longer complains and editors can show propose code completions. E.g. VS Code:

<img width="1230" alt="image" src="https://user-images.githubusercontent.com/988276/118273881-c3699b80-b4c4-11eb-86f9-f122b9778cfc.png">

*Limitations*

This is just a very specific case. The proper definition of `$$restProps` in other components is subject to further work.
As an alternative to `svelte.JSX.HTMLAttributes` I would like to suggest [`Partial`](https://www.typescriptlang.org/docs/handbook/utility-types.html#partialtype) in a separate PR.

2021-06-15 14:49 UTC, metonym requested changes
Thanks for catching this.

The TypeScript definitions are auto-generated and should not be edited directly.

I'd suggest adding `@restProps {input}` as a comment to `ToolbarSearch.svelte`. 

Here's an example: https://github.com/IBM/carbon-components-svelte/blob/master/src/Button/Button.svelte#L4

2021-06-15 21:42 UTC, gregorw commented
Thanks for taking the time to respond. I have updated the PR as you suggested. So, it’s analogous to:

https://github.com/IBM/carbon-components-svelte/blob/cff16e5d7de19652df6a905360bbfe01ea6d0d7f/src/Tag/Tag.svelte#L2

Great tooling by the way. I’m Impressed by sveld.

2021-06-15 22:13 UTC, metonym approved these changes
Great work – thank you for your patience.

2021-06-15 22:13 UTC, merged

2021-06-25 11:07 UTC, metonym commented
Available in v0.34.0 ([release notes](https://github.com/IBM/carbon-components-svelte/releases/tag/v0.34.0))